server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auto_rental?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  # 这里的配置是针对请求体也就是json字符串中的时间的转化进行配置
  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Shanghai
  mvc:
    # 这里的配置是针对请求参数中的时间转化进行配置
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
    # 解决swagger3的配置问题
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 10000
      expire: 60000
mybatis-plus:
  configuration:
    # 配置打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置mapper的位置，使得在编译的时候能够找到这些xml文件
  mapper-locations: classpath*:/mapper/**/*.xml
  # 为实体类设置别名
  type-aliases-package: com.coder.entity
  global-config:
    db-config:
      # 设置逻辑删除字段
      logic-delete-field: deleted

encoder:
  ctype:
    strength: 6
    secret: ${random.uuid}

request:
  loginUrl: /rental/user/login